### ISSUE TITLE
V68 DepthAPI flickering and unstable behaviour

### ISSUE THREAD

**Issue by Squashi11** [oculus-samples/Unity-DepthAPI#48] opened 2024-07-19 10:25 UTC
After updating my headset to V68 , the depth api works 50/50 and when it doesnt it flickers behind walls etc
using unity 6000.0.11f1

**Comment by GitHubUsername1** [comment] 2024-07-19 11:09
Hey I've noticed this this morning too I think, please see my video of it :

https://youtube.com/shorts/kTuenO0r3Ko

I've changed nothing my end in my code, it was working up until I tried it this morning, I'm on V68 too (it's just updated).

**Comment by TudorJude** [comment] 2024-07-19 11:27
Hello,

Depth API has changed quite significantly in the last update. Meta core sdk reflects these changes already, I'm working on updating this github repo's code and docs right now and should be available later today.

Apologies for any inconvenience.

**Comment by Squashi11** [comment] 2024-07-19 11:28
Thanks for the reply! Will it be working Unity 6000?

**Comment by TudorJude** [comment] 2024-07-19 11:31
Unity 6000 seems to still be in preview, so master will still not support it. I will, however, rebase the Unity 6000 branch fix on top of master, so it should work just fine for you once I do.

**Comment by GitHubUsername1** [comment] 2024-07-19 11:53
> Could you please clarify what version of OS you upgraded from when experiencing this issue?

I'm on Quest 3 V68 firmware, Meta All In One SDK V66, experiencing this issue from a few hours ago, the only thing I've noticed that changed is that I'm on V68 Quest 3 firmware, I have changed nothing in my apps code.

**Comment by TudorJude** [comment] 2024-07-19 12:07
Would you mind sharing an apk with us? We want to double-check if the issue is unique to the particular OS you are on. Can you also share the detailed version for you OS?

**Comment by GitHubUsername1** [comment] 2024-07-19 12:13
> Would you mind sharing an apk with us? We want to double-check if the issue is unique to the particular OS you are on. Can you also share the detailed version for you OS?

I can share an apk via a google drive link but I can't post it publically as my app is a paid for app on Patreon, if you can give me an email address to email you the google drive link I can do that no problem. Here is the detailed OS version : https://ibb.co/9GjNRc1

**Comment by TudorJude** [comment] 2024-07-19 12:38
We've managed to reproduce the issue, it seems to be OS related. Thank you for flagging this issue.

**Comment by GitHubUsername1** [comment] 2024-07-23 04:20
> I am keeping this issue open, since the actual fix will come in a future OS update. Once it is out I will update this thread.

Hi, does this mean that rather than editing scripts etc as suggested in section 11 on this Githubs readme, I can just wait until the next OS update and this issue will be fixed?

**Comment by TudorJude** [comment] 2024-07-23 07:25
Yes, the update to the OS should land very soon and the flicker issues will be fixed. That being said, I would still recommend to update to the v67 version of the sdks. Soft occlusions will look better and will be have improved performance.

**Comment by GitHubUsername1** [comment] 2024-07-23 09:26
Good to know. I have tried and I am still in the process of refactoring my code to work with the V67's. The avatars in my app are being dynamically occluded and I agree the occlusions looked a lot better, unfortunately though the background, where the passthrough was being displayed, was being rendered pink, so something I'm doing isn't right. I'll carry on trying to apply the changes while waiting for the Meta OS update. Thanks.

**Comment by TudorJude** [comment] 2024-08-02 09:11
Updating to the latest version of v68 will completely solve this issue for anyone experiencing further flickering.

**Closed by TudorJude** 2024-08-02 09:11 UTC
